# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "comments", :force => true do |t|
    t.column "commentable_type", :string, :default => "", :null => false
    t.column "commentable_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer
    t.column "body", :string, :limit => 1000, :default => "", :null => false
    t.column "created_on", :datetime
  end

  add_index "comments", ["commentable_type", "commentable_id"], :name => "comments_commentable_type_index"

  create_table "courses", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "subject_id", :integer, :default => 0, :null => false
    t.column "subject_code", :string, :limit => 30
    t.column "number", :string, :limit => 10, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "credit", :float, :default => 0.0
    t.column "description", :string, :limit => 5000
    t.column "creator_id", :integer
    t.column "status", :enum, :limit => [:pending, :approved, :rejected, :retiered]
    t.column "created_on", :date
    t.column "updated_on", :date
  end

  add_index "courses", ["school_id", "subject_id", "number"], :name => "courses_school_id_index", :unique => true
  add_index "courses", ["school_id", "name", "number"], :name => "index_on_name"
  add_index "courses", ["school_id", "subject_code", "number"], :name => "index_on_subject_code"

  create_table "document_files", :force => true do |t|
    t.column "document_id", :integer, :default => 0, :null => false
    t.column "file_name", :string, :limit => 500
  end

  add_index "document_files", ["document_id"], :name => "document_files_document_id_index"

  create_table "documents", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "course_id", :integer, :default => 0, :null => false
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "comment", :string, :limit => 500
    t.column "links", :string, :limit => 30000
    t.column "anonymous", :enum, :limit => [:y]
    t.column "num_views", :integer, :default => 0
    t.column "updated_on", :datetime
    t.column "semester_id", :integer, :default => 0
    t.column "privacy", :string, :limit => 20
    t.column "created_on", :datetime, :null => false
  end

  add_index "documents", ["title", "privacy"], :name => "documents_title_index"
  add_index "documents", ["school_id", "privacy"], :name => "documents_school_id_index"
  add_index "documents", ["course_id", "privacy"], :name => "documents_course_id_index"
  add_index "documents", ["privacy"], :name => "documents_privacy_index"

  create_table "group_networks", :force => true do |t|
    t.column "group_id", :integer
    t.column "network_id", :integer
    t.column "network_type", :string
  end

  add_index "group_networks", ["network_id", "network_type"], :name => "group_networks_network_id_index"

  create_table "groups", :force => true do |t|
    t.column "school_id", :integer
    t.column "creator_id", :integer
    t.column "name", :string, :limit => 100
    t.column "type", :string, :limit => 100
    t.column "desc", :string, :limit => 500
    t.column "access", :string, :limit => 30
    t.column "students_only", :boolean
    t.column "portal_view", :boolean, :default => true
    t.column "pic", :string, :limit => 100
    t.column "created_on", :date
  end

  create_table "groups_users", :force => true do |t|
    t.column "group_id", :integer
    t.column "user_id", :integer
    t.column "admin", :boolean
    t.column "blocked", :boolean
    t.column "created_on", :date
  end

  create_table "invites", :force => true do |t|
    t.column "inviter_id", :integer, :default => 0, :null => false
    t.column "invitee_id", :integer
    t.column "klass_id", :integer
    t.column "invite_type", :string, :limit => 20
    t.column "app_user", :enum, :limit => [:y]
    t.column "fb_user", :enum, :limit => [:y]
    t.column "name", :string, :limit => 100
    t.column "email", :string, :limit => 100
    t.column "updated_on", :datetime
  end

  add_index "invites", ["inviter_id", "invitee_id", "invite_type"], :name => "invites_inviter_id_index"

  create_table "klass_schedules", :force => true do |t|
    t.column "klass_id", :integer, :default => 0, :null => false
    t.column "start_time", :string, :limit => 5, :default => "", :null => false
    t.column "day_of_week", :enum, :limit => [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
    t.column "end_time", :string, :limit => 5, :default => "", :null => false
  end

  add_index "klass_schedules", ["start_time", "end_time", "day_of_week", "klass_id"], :name => "klass_schedules_start_time_index", :unique => true

  create_table "klasses", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "course_id", :integer, :default => 0, :null => false
    t.column "semester_id", :integer, :default => 0, :null => false
    t.column "room", :string, :limit => 30
    t.column "division", :integer, :limit => 6, :default => 0, :null => false
    t.column "created_on", :date
    t.column "updated_on", :date
    t.column "creator_id", :integer
    t.column "status", :enum, :limit => [:pending, :approved, :rejected]
    t.column "section", :string, :limit => 15
  end

  add_index "klasses", ["school_id", "course_id", "semester_id"], :name => "klasses_school_id_index"
  add_index "klasses", ["course_id", "semester_id"], :name => "klasses_course_id_index"
  add_index "klasses", ["school_id", "semester_id"], :name => "school_id1"

  create_table "klasses_users", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "semester_id", :integer, :default => 0, :null => false
    t.column "klass_id", :integer, :default => 0, :null => false
    t.column "course_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
    t.column "created_on", :datetime, :null => false
  end

  add_index "klasses_users", ["user_id", "semester_id"], :name => "user_id_1"
  add_index "klasses_users", ["user_id", "klass_id"], :name => "user_id_2"

  create_table "posts", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "reply_id", :integer
    t.column "topic_id", :integer, :default => 0, :null => false
    t.column "body", :string, :limit => 2000, :default => "", :null => false
    t.column "is_first_post", :boolean
    t.column "is_anonymous", :boolean
    t.column "created_on", :datetime
    t.column "last_updated", :datetime
  end

  add_index "posts", ["topic_id"], :name => "posts_topic_id_index"

  create_table "promos", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "code", :string
    t.column "counter", :integer, :default => 0
  end

  add_index "promos", ["user_id"], :name => "promos_user_id_index", :unique => true

  create_table "reports", :force => true do |t|
    t.column "reportable_type", :string, :default => "", :null => false
    t.column "reportable_id", :integer, :default => 0, :null => false
    t.column "reporter_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "resolved", :boolean
    t.column "subject", :string, :limit => 100, :default => "", :null => false
    t.column "body", :string, :limit => 1000, :default => "", :null => false
    t.column "created_on", :datetime
  end

  add_index "reports", ["reportable_type", "reportable_id"], :name => "reports_reportable_type_index"

  create_table "requested_schools", :force => true do |t|
    t.column "nid", :integer, :default => 0, :null => false
    t.column "name", :string
    t.column "user_id", :integer
  end

  add_index "requested_schools", ["nid", "name", "user_id"], :name => "requested_schools_nid_index", :unique => true

  create_table "roles", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "parent_id", :integer
    t.column "lft", :integer
    t.column "rgt", :integer
  end

  add_index "roles", ["name"], :name => "name", :unique => true

  create_table "schools", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "city", :string, :limit => 100, :default => "", :null => false
    t.column "region", :string, :limit => 100, :default => "", :null => false
    t.column "country", :string, :limit => 100, :default => "", :null => false
    t.column "created_on", :datetime
    t.column "closed", :boolean
    t.column "loaded", :boolean, :default => false
    t.column "sem_loaded", :boolean, :default => false
  end

  create_table "schools_users", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
    t.column "account_status", :enum, :limit => [:activated, :fb_status_changed, :suspended]
    t.column "fb_status", :string, :limit => 30
    t.column "updated_on", :datetime
  end

  add_index "schools_users", ["user_id", "school_id"], :name => "schools_users_user_id_index", :unique => true

  create_table "seasons", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 30
    t.column "parent_id", :integer
    t.column "lft", :integer
    t.column "rgt", :integer
    t.column "start_str", :string, :limit => 5
    t.column "end_str", :string, :limit => 5
    t.column "deleted", :boolean, :default => false
  end

  add_index "seasons", ["school_id", "name"], :name => "school_id", :unique => true

  create_table "semesters", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "season_id", :integer, :default => 0, :null => false
    t.column "start_date", :datetime
    t.column "end_date", :datetime
    t.column "deleted", :boolean, :default => false
  end

  add_index "semesters", ["school_id", "start_date", "end_date"], :name => "uniq_semesters", :unique => true

  create_table "settings", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "name", :string
    t.column "context_id", :integer, :default => 0, :null => false
    t.column "context_type", :string
    t.column "bool_val", :boolean
    t.column "val", :string
  end

  add_index "settings", ["user_id", "name", "context_type", "context_id"], :name => "settings_user_id_index", :unique => true

  create_table "subjects", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "code", :string, :limit => 30, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "creator_id", :integer
    t.column "status", :enum, :limit => [:pending, :approved, :rejected, :retiered]
    t.column "created_on", :date
    t.column "updated_on", :date
  end

  add_index "subjects", ["code", "name", "school_id"], :name => "subjects_code_index", :unique => true

  create_table "syndicates", :force => true do |t|
    t.column "user_id", :integer
    t.column "news_type", :string
    t.column "story_partial", :string
    t.column "story_locals", :binary
    t.column "context_type", :string
    t.column "context_id", :string
    t.column "created_on", :datetime
  end

  add_index "syndicates", ["context_type", "context_id"], :name => "syndicates_context_type_index"
  add_index "syndicates", ["user_id", "context_type", "context_id"], :name => "syndicates_user_id_index"

  create_table "taggings", :force => true do |t|
    t.column "tag_id", :integer
    t.column "taggable_id", :integer
    t.column "taggable_type", :string
    t.column "created_at", :datetime
  end

  add_index "taggings", ["tag_id"], :name => "taggings_tag_id_index"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "taggings_taggable_id_index"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "topics", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "discussable_id", :integer, :default => 0, :null => false
    t.column "discussable_type", :string, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "body", :string, :limit => 3000, :default => "", :null => false
    t.column "is_anonymous", :boolean
    t.column "created_on", :datetime
    t.column "last_updated", :datetime
  end

  add_index "topics", ["discussable_id", "discussable_type"], :name => "topics_discussable_id_index"

  create_table "users", :force => true do |t|
    t.column "account_status", :enum, :limit => [:activated, :suspended, :deactivated]
    t.column "created_on", :datetime
    t.column "profile_updated_on", :datetime
    t.column "access_time", :datetime
  end

  create_table "v_klasses", :force => true do |t|
    t.column "school_id", :integer, :default => 0, :null => false
    t.column "subject_id", :integer, :default => 0, :null => false
    t.column "subject_code", :string, :limit => 30
    t.column "number", :string, :limit => 10, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "credit", :float, :default => 0.0
    t.column "description", :string, :limit => 5000
    t.column "creator_id", :integer
    t.column "status", :enum, :limit => [:pending, :approved, :rejected, :retiered]
    t.column "created_on", :date
    t.column "updated_on", :date
  end

end
